### ISSUE TITLE
Problemi Importanti di SEMANTICA sulla Pagina WCAG

### ISSUE THREAD

**Issue by Denel91** [omar-polo/progettazione-siti-web#9]
Ho riscontrato un problema importante nella pagina del WCAG...Allora attenzione:
**Ti mostro la situazione attuale:**
    Linee guida per l’accessibilità dei contenuti Web --> h1
            Introduzione --> h5
            Perimetro dell’indagine --> h5
            Requisiti di conformità --> h5
           Glossario -- h5
           Risultati del report --> h5
           Sommario dei risultati --> h5
           Dettagli del report --> h5
           Indice dei contenuti --> h6

**Come credo sarebbe corretto agire:**
Linee guida per l’accessibilità dei contenuti Web --> h1
            Introduzione --> h2
            Perimetro dell’indagine --> h3
            Requisiti di conformità --> h4
            Glossario -->h5
            Risultati del report --> h6
            Sommario dei risultati --> h7
            Dettagli del report --> h8
            Indice dei contenuti --> h9

Fammi sapere come la pensi!

**Comment by omar-polo** [comment]
Ni, credo che si possa migliorare ancora (anche perché gli headings arrivano solo fino al 6 lol)

> linee guida per l’accessibilità dei contenuti Web -> h1
> Introduzione -> h2
> Perimetro dell’indagine -> h3
> Requisiti di conformità -> h3
> Glossario ->h3
> Risultati del report -> h3
> Sommario dei risultati -> h3
> Dettagli del report -> h3
> Indice dei contenuti -> h2/h3

Questo perché il perimetro dell'indagine, i requisiti, il glossario, i risultati, il sommario e i dettagli sono tutte sezioni allo stesso livello (i requisiti di conformità non sono una sotto sezione del perimetro d'indagine secondo me)

Ho un dubbio ancora per quanto riguarda l'indice...

**Comment by omar-polo** [comment]
Resta comunque il discorso che la numerazione va fixata. Lo farò domattina. Non creo una inssue per quello perché sarebbe più lo smetto di crearla e chiuderla che non implementarlo ahahaha
